version: "3.6"
services:
  zookeeper:
    image: "zookeeper:3.5.6"
    container_name: zookeeper
    networks:
      - ms-network
  kafka:
    image: "wurstmeister/kafka:2.12-2.3.0"
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "public_messages:1:1"
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
    networks:
      - ms-network
networks:
  ms-network:
    name: ms-network
